version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks: ['puzzles']
  puzzles:
    build: .
    container_name: puzzles
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
    - "8888:8888"
    networks: ['puzzles']

volumes:
    esdata:
        external: true

networks:
  puzzles:
    driver: bridge